In [18]:
# First try it to do it without time-depedencies with average
import numpy as np
import pandas as pd
from datetime import datetime
import os


chunksize = 10000
i = 1
j = 1
number_of_areas = 265
array = np.zeros(number_of_areas**2).reshape(number_of_areas,number_of_areas)

#if (os.path.isfile('matrix.txt')):
#    os.remove('matrix.txt')

# loop for all start-to-end-areas (should they be saved?)

while (i <= number_of_areas):
    while (j <= number_of_areas):
        a = 0
        summe = 0
        counter = 0
        average = 0
        for chunk in pd.read_csv('short_tripdata.csv', chunksize = chunksize):
            while(a < chunksize):
                if (chunk['PULocationID'][a] == i and chunk['DOLocationID'][a] == j):
                    summe += chunk['trip_distance'][a]
                    counter += 1
            
                a += 1
                #print(i , j , a)
        # write in matrix
        
        if(counter != 0):
            array[i,j] = summe / counter
            print(i,j)
        
        # write an array
        
        # write in the .txt file
        #matrix = open("matrix.txt","a")
        #if (counter != 0):
        #    average = summe / counter 
        #matrix.write(str(average))
        
        #print(i , j , a)
        
        j += 1
    print(i , j , a)
    i += 1
    j = 0


        



1 266 10000
2 266 10000
3 226
3 266 10000
4 79
4 87
4 107
4 113
4 114
4 137
4 148
4 170
4 211
4 229
4 234
4 237
4 246
4 266 10000


KeyboardInterrupt: 

In [22]:
print(array)
print(array[4,237])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
3.32


In [12]:
import numpy as np

number_of_areas = 265
array = np.zeros(265*265).reshape(number_of_areas,number_of_areas)
print (array)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [37]:
with open('test.txt', 'w') as outfile:
    # I'm writing a header here just for the sake of readability
    # Any line starting with "#" will be ignored by numpy.loadtxt
    outfile.write('# Array shape: {0}\n'.format(array.shape))

    # Iterating through a ndimensional array produces slices along
    # the last axis. This is equivalent to data[i,:,:] in this case
    #for data_slice in array:

        # The formatting string indicates that I'm writing out
        # the values in left-justified columns 7 characters in width
        # with 2 decimal places.  
    np.savetxt(outfile, array, fmt='%-4.2f')

        # Writing out a break to indicate different slices...
    outfile.write('# New slice\n')