In [81]:
# Solving time dependent

import numpy as np
import matplotlib.pyplot as plt
from docplex.mp.model import Model
import docplex.mp.solution as Solution

# for sequentiel solving 

from itertools import product

#cost = np.loadtxt('dependent_2017to2019_15min_withouthashtag.txt')
#cost = np.reshape(cost,(48,91,91))
cost = np.random.rand(48,91,91) * 10

print(cost)

############# continue here

cities=[i for i in range(len(cost))]
#print(cities)
arcs =[(i,j) for i in cities for j in cities if i!=j]


distance={(i, j): cost[i,j] for i,j in arcs}
#print(distance)

# CPLEX model
mdl=Model('TSP')

# decision variables

x=mdl.binary_var_dict(arcs,name='x')
d=mdl.continuous_var_dict(cities,name='d')

mdl.minimize(mdl.sum(distance[i]*x[i] for i in arcs))

# Constraints
for c in cities:
    mdl.add_constraint(mdl.sum(x[(i,j)] for i,j in arcs if i==c)==1, 
                       ctname='out_%d'%c)
    
for c in cities:
    mdl.add_constraint(mdl.sum(x[(i,j)] for i,j in arcs if j==c)==1, 
                       ctname='in_%d'%c)

    
# conventional way to eliminate subtours (Dantzig, Fulkerson and Johnson)
for i,j in arcs:
    if j!=0:
        mdl.add_indicator(x[(i,j)],d[i]+1==d[j], 
                          name='order_(%d,_%d)'%(i, j))
        
        
print(mdl.export_to_string())

# possible to add constraint

mdl.parameters.timelimit=120
mdl.parameters.mip.strategy.branch=1
mdl.parameters.mip.tolerances.mipgap=0.15

solution = mdl.solve(log_output=True)

mdl.get_solve_status()

solution.display()


[[[1.30996845 8.09490692 3.44736653 ... 9.16305553 9.09635525 2.57118294]
  [1.10891301 1.92962732 4.99584171 ... 8.03960891 0.32323067 7.09387251]
  [4.65001482 9.47548941 2.21432734 ... 4.26474789 2.47396037 3.71293761]
  ...
  [1.58347145 5.90509086 6.38005953 ... 2.86086444 5.50364474 0.07206774]
  [9.50888822 4.38235453 3.56145071 ... 2.73709241 4.53676469 8.95617035]
  [2.04043058 1.13638347 6.18168934 ... 1.24699611 8.55707907 9.33883945]]

 [[6.48654279 1.84974048 7.223253   ... 7.23760228 1.54939105 5.69318606]
  [5.29554868 9.39542037 6.92623234 ... 7.81009955 5.10238159 6.0696214 ]
  [2.8245125  9.35996038 6.16869062 ... 6.9429233  0.2957906  0.87270653]
  ...
  [7.17612626 3.03591455 4.08678276 ... 4.89920328 6.54538369 7.21105579]
  [1.02041302 0.76087535 4.81682942 ... 9.39165631 2.32326058 9.10438939]
  [7.85212743 5.86783368 3.54130212 ... 2.68533031 1.91656593 9.85902006]]

 [[3.45673036 2.69981975 3.81044225 ... 2.38080492 5.04235729 2.58308551]
  [5.73683675 6.991557

In [76]:
# Solving time independent

import numpy as np
import matplotlib.pyplot as plt
from docplex.mp.model import Model
import docplex.mp.solution as Solution

# for sequentiel solving 

from itertools import product

cost = np.loadtxt('matrix_time-independent_2017to2019_delete.txt')

cities=[i for i in range(len(cost))]
#print(cities)
arcs =[(i,j) for i in cities for j in cities if i!=j]


distance={(i, j): cost[i,j] for i,j in arcs}
#print(distance)

# CPLEX model
mdl=Model('TSP')

# decision variables

x=mdl.binary_var_dict(arcs,name='x')
d=mdl.continuous_var_dict(cities,name='d')

mdl.minimize(mdl.sum(distance[i]*x[i] for i in arcs))

# Constraints
for c in cities:
    mdl.add_constraint(mdl.sum(x[(i,j)] for i,j in arcs if i==c)==1, 
                       ctname='out_%d'%c)
    
for c in cities:
    mdl.add_constraint(mdl.sum(x[(i,j)] for i,j in arcs if j==c)==1, 
                       ctname='in_%d'%c)

    
# conventional way to eliminate subtours (Dantzig, Fulkerson and Johnson)
for i,j in arcs:
    if j!=0:
        mdl.add_indicator(x[(i,j)],d[i]+1==d[j], 
                          name='order_(%d,_%d)'%(i, j))
        
        
print(mdl.export_to_string())

# possible to add constraint

mdl.parameters.timelimit=120
mdl.parameters.mip.strategy.branch=1
mdl.parameters.mip.tolerances.mipgap=0.15

solution = mdl.solve(log_output=True)

mdl.get_solve_status()

solution.display()


\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: TSP

Minimize
 obj: 13.420000000000 x_0_1 + 3.450000000000 x_0_2 + 10.720000000000 x_0_3
      + 19.200000000000 x_0_4 + 4.570000000000 x_0_5 + 13.200000000000 x_0_6
      + 11.610000000000 x_0_7 + 12.960000000000 x_0_8 + 9.830000000000 x_0_9
      + 17.120000000000 x_0_10 + 4.190000000000 x_0_11 + 5.710000000000 x_0_12
      + 4.820000000000 x_0_13 + 11.960000000000 x_0_14 + 7.410000000000 x_0_15
      + 8.140000000000 x_0_16 + 4.940000000000 x_0_17 + 10.090000000000 x_0_18
      + 5 x_0_19 + 4.380000000000 x_0_20 + 16.340000000000 x_0_21
      + 5.030000000000 x_0_22 + 14.620000000000 x_0_23 + 10.140000000000 x_0_24
      + 6.590000000000 x_0_25 + 11.360000000000 x_0_26 + 4.170000000000 x_0_28
      + 4.030000000000 x_0_29 + 10.870000000000 x_0_30 + 2.660000000000 x_0_31
      + 10.370000000000 x_0_32 + 9 x_0_33 + 13.290000000000 x_0_34
      + 5.670000000000 x_0_35 + 12.370000000000 x_0_36 + 10.9200000000

CPXPARAM_Read_DataCheck                          1
CPXPARAM_RandomSeed                              202001241
CPXPARAM_MIP_Strategy_Branch                     1
CPXPARAM_TimeLimit                               120
CPXPARAM_MIP_Tolerances_MIPGap                   0.14999999999999999
Tried aggregator 2 times.
MIP Presolve modified 6670 coefficients.
Aggregator did 6670 substitutions.
Reduced MIP has 7020 rows, 20475 columns, and 47502 nonzeros.
Reduced MIP has 13572 binaries, 0 generals, 0 SOSs, and 13456 indicators.
Presolve time = 0.08 sec. (300.08 ticks)
Probing time = 0.03 sec. (33.67 ticks)
Tried aggregator 1 time.
Detecting symmetries...
Reduced MIP has 7020 rows, 20475 columns, and 47502 nonzeros.
Reduced MIP has 13572 binaries, 0 generals, 0 SOSs, and 13456 indicators.
Presolve time = 0.03 sec. (32.41 ticks)
Probing time = 0.02 sec. (8.24 ticks)
Clique table members: 6904.
MIP emphasis: balance optimality and feasibility.
MIP search method: dynamic search.
Parallel mode: determin

In [16]:
# testdata

import numpy as np

test = np.random.rand(10,10) * 100

print(test)

np.savetxt('test.txt', test, fmt='%-4.2f')

[[29.4347901   8.20758003 29.10196074 72.26923591 22.992751   12.49573891
  19.73883223 22.89879464 11.79526477 72.54448897]
 [85.95343714 42.86686349  7.63407884 40.29326144  2.04140725 78.27410305
   7.96230243 19.9709607  47.97561912  0.1324633 ]
 [64.36273156 13.67748046 51.13256728 67.96376069 49.24307182 69.9642299
  14.77743171 89.17367447 99.1918     88.03598032]
 [84.08563954  5.76651227 28.02890045 50.57124431 64.65656705 29.82816721
  70.84065227 78.28381715 90.31745547 91.4240113 ]
 [92.71868447 34.89122347  3.92211883  9.00333898 28.04198931 73.19203986
  76.89485575 89.08057956 40.88895342 88.72292306]
 [15.33648129 80.13912192 86.99239293 11.47276369 26.73041584 88.53223331
  56.46494295 42.39599126 56.68660673  5.2528669 ]
 [ 0.62580905 30.48535235 23.39955139 78.6771767  81.88049763 81.52303494
  11.78178821 44.80112531 76.33897545 10.5030909 ]
 [40.63860027 81.32164563 65.66464617 83.3495674  13.21381383 70.01372946
  69.32495192 55.01488108 67.52053148 34.84805028]
 

In [ ]:
Implement sequential formulation in TSP (Miller, Tucker, Zemlin)